__version__      = '0.2.1'
__description__  = 'Helpers and utilities to be used with lxml'
__url__          = 'https://github.com/innodatalabs/lxmlx'
__author__       = 'Mike Kroutikov'
__author_email__ = 'mkroutikov@innodata.com'
__keywords__     = 'lxml xml events sax'
